"""Edit Testtable

Revision ID: 5fb88433c910
Revises: 8d5bb0923d72
Create Date: 2024-02-08 12:04:04.173234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb88433c910'
down_revision = '8d5bb0923d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_table', schema=None) as batch_op:
        batch_op.alter_column('vehicle_part',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=550),
               existing_nullable=True)
        batch_op.alter_column('part_code_requirement',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=550),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_table', schema=None) as batch_op:
        batch_op.alter_column('part_code_requirement',
               existing_type=sa.String(length=550),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('vehicle_part',
               existing_type=sa.String(length=550),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
