"""Edit Testtable

Revision ID: 76cbe1c37adb
Revises: 3de441f3a2fa
Create Date: 2024-02-08 11:53:38.225109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cbe1c37adb'
down_revision = '3de441f3a2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('final_table', schema=None) as batch_op:
        batch_op.alter_column('part_code_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=550),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('final_table', schema=None) as batch_op:
        batch_op.alter_column('part_code_name',
               existing_type=sa.String(length=550),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
