"""Edit Testtable

Revision ID: 8d5bb0923d72
Revises: 2442855a04cc
Create Date: 2024-02-08 12:03:19.237219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5bb0923d72'
down_revision = '2442855a04cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_table', schema=None) as batch_op:
        batch_op.alter_column('part_code_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=550),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_table', schema=None) as batch_op:
        batch_op.alter_column('part_code_name',
               existing_type=sa.String(length=550),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
